using System.Globalization;
using System.Text;
using Microsoft.EntityFrameworkCore;
using Northwind.Mvc.Models;

namespace Northwind.Mvc.Services;

public class SimplePdfService(CateringProjectContext db) : IPdfService
{
    private static readonly CultureInfo Tr = CultureInfo.GetCultureInfo("tr-TR");

    public async Task<byte[]> CreateReceiptAsync(int orderId)
    {
        var order = await LoadOrder(orderId);
        var pdf = BrandedPdf.Create($"Receipt #{order.Id}");

        pdf.Header("Receipt", $"Order #{order.Id}", order.CreatedUtc);
        pdf.InfoGrid([
            ("Bill To", order.Customer?.DisplayName ?? "-"),
            ("Caterer", order.Caterer?.Name ?? "-"),
            ("Status", order.Status),
            ("Event Address", string.IsNullOrWhiteSpace(order.DeliveryAddress) ? "-" : order.DeliveryAddress!)
        ]);

        pdf.SectionTitle("Order Summary");
        pdf.TableHeader(["Menu package", "Guests", "Per person", "Line total"], [245, 70, 95, 95]);

        foreach (var line in order.Lines)
        {
            var optionText = line.AppliedOptions.Any()
                ? "Add-ons: " + string.Join(", ", line.AppliedOptions.Select(o => o.OptionLabel))
                : "Standard setup";

            pdf.TableRow([
                $"{line.MenuItem?.Name ?? "Menu"}\n{optionText}",
                line.Quantity.ToString(CultureInfo.InvariantCulture),
                Money(line.UnitPrice),
                Money(line.UnitPrice * line.Quantity)
            ], [245, 70, 95, 95]);
        }

        pdf.TotalBox("Total Paid", Money(order.TotalAmount));
        pdf.Note("This receipt was generated by Vellora Catering & Events for the confirmed catering order above.");
        pdf.Footer(order.Id);
        return pdf.ToBytes();
    }

    public async Task<byte[]> CreateAgreementAsync(int orderId)
    {
        var order = await LoadOrder(orderId);
        var pdf = BrandedPdf.Create($"Agreement #{order.Id}");

        pdf.Header("Catering Agreement", $"Order #{order.Id}", order.CreatedUtc);
        pdf.InfoGrid([
            ("Customer", order.Customer?.DisplayName ?? "-"),
            ("Caterer", order.Caterer?.Name ?? "-"),
            ("Event Address", string.IsNullOrWhiteSpace(order.DeliveryAddress) ? "-" : order.DeliveryAddress!),
            ("Agreement Status", order.Status)
        ]);

        pdf.SectionTitle("Selected Menu Packages");
        pdf.TableHeader(["Menu package", "Guests", "Per person", "Subtotal"], [245, 70, 95, 95]);
        foreach (var line in order.Lines)
        {
            pdf.TableRow([
                $"{line.MenuItem?.Name ?? "Menu"}\n{Clean(line.CustomizationSummary, "Standard setup")}",
                line.Quantity.ToString(CultureInfo.InvariantCulture),
                Money(line.UnitPrice),
                Money(line.UnitPrice * line.Quantity)
            ], [245, 70, 95, 95]);
        }

        pdf.TotalBox("Agreement Total", Money(order.TotalAmount));
        pdf.SectionTitle("Terms");
        pdf.NumberedTerms([
            "The caterer will prepare the selected catering menu after simulated payment confirmation.",
            "Guest count is used as the billing quantity. Add-ons are calculated per guest where applicable.",
            "The customer is responsible for providing accurate delivery and event details before service.",
            "This demo agreement is generated for coursework and does not process real payment."
        ]);

        if (!string.IsNullOrWhiteSpace(order.EventNotes))
        {
            pdf.SectionTitle("Event Notes");
            pdf.Paragraph(order.EventNotes!);
        }

        pdf.SignatureLines("Customer Signature", "Caterer Signature");
        pdf.Footer(order.Id);
        return pdf.ToBytes();
    }

    private Task<OrderEntity> LoadOrder(int orderId) =>
        db.Orders
            .Include(o => o.Customer)
            .Include(o => o.Caterer)
            .Include(o => o.Lines).ThenInclude(l => l.MenuItem)
            .Include(o => o.Lines).ThenInclude(l => l.AppliedOptions)
            .FirstAsync(o => o.Id == orderId);

    private static string Money(decimal value) => value.ToString("C0", Tr);

    private static string Clean(string? value, string fallback) =>
        string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();

    private sealed class BrandedPdf
    {
        private readonly StringBuilder content = new();
        private readonly string documentTitle;
        private double y = 742;

        private BrandedPdf(string documentTitle) => this.documentTitle = documentTitle;

        public static BrandedPdf Create(string title) => new(title);

        public void Header(string documentType, string reference, DateTime createdUtc)
        {
            Fill(0.12, 0.05, 0.05);
            Rect(0, 730, 612, 62, fill: true);
            Fill(0.77, 0.58, 0.26);
            CircleApprox(52, 761, 15);
            Text("V", 46, 753, 20, "F2", 0.77, 0.58, 0.26);
            Text("VELLORA", 76, 766, 21, "F2", 1, 0.95, 0.84);
            Text("CATERING & EVENTS", 77, 748, 8, "F1", 0.77, 0.58, 0.26);
            Text(documentType.ToUpperInvariant(), 390, 765, 18, "F2", 1, 0.95, 0.84);
            Text(reference, 391, 747, 10, "F1", 0.9, 0.82, 0.68);
            Text(createdUtc.ToLocalTime().ToString("dd MMM yyyy HH:mm", Tr), 391, 733, 9, "F1", 0.9, 0.82, 0.68);
            y = 690;
        }

        public void InfoGrid(IReadOnlyList<(string Label, string Value)> items)
        {
            var width = 250.0;
            var height = 58.0;
            for (var i = 0; i < items.Count; i++)
            {
                var col = i % 2;
                var row = i / 2;
                var x = 50 + col * 270;
                var boxY = y - row * 72;
                Stroke(0.82, 0.74, 0.58);
                Rect(x, boxY - height, width, height, fill: false);
                Text(items[i].Label.ToUpperInvariant(), x + 12, boxY - 18, 8, "F2", 0.5, 0.38, 0.18);
                WrappedText(items[i].Value, x + 12, boxY - 35, width - 24, 10, "F1", 0.12, 0.08, 0.07, 2);
            }
            y -= 150;
        }

        public void SectionTitle(string title)
        {
            EnsureSpace(52);
            Text(title, 50, y, 15, "F2", 0.28, 0.04, 0.08);
            Stroke(0.77, 0.58, 0.26);
            Line(50, y - 8, 562, y - 8);
            y -= 28;
        }

        public void TableHeader(string[] headers, int[] widths)
        {
            EnsureSpace(36);
            Fill(0.28, 0.04, 0.08);
            Rect(50, y - 24, 512, 24, fill: true);
            var x = 60.0;
            for (var i = 0; i < headers.Length; i++)
            {
                Text(headers[i].ToUpperInvariant(), x, y - 16, 8, "F2", 1, 0.95, 0.84);
                x += widths[i];
            }
            y -= 30;
        }

        public void TableRow(string[] values, int[] widths)
        {
            EnsureSpace(54);
            var rowTop = y;
            Stroke(0.88, 0.84, 0.76);
            Line(50, rowTop + 8, 562, rowTop + 8);
            var x = 60.0;
            for (var i = 0; i < values.Length; i++)
            {
                WrappedText(values[i], x, rowTop - 6, widths[i] - 12, 9, i == 0 ? "F2" : "F1", 0.12, 0.08, 0.07, i == 0 ? 2 : 1);
                x += widths[i];
            }
            y -= 48;
        }

        public void TotalBox(string label, string total)
        {
            EnsureSpace(58);
            Stroke(0.77, 0.58, 0.26);
            Rect(352, y - 44, 210, 44, fill: false);
            Text(label.ToUpperInvariant(), 366, y - 17, 8, "F2", 0.5, 0.38, 0.18);
            Text(total, 455, y - 30, 18, "F2", 0.28, 0.04, 0.08);
            y -= 70;
        }

        public void NumberedTerms(IReadOnlyList<string> terms)
        {
            foreach (var term in terms.Select((value, index) => new { value, index }))
            {
                EnsureSpace(34);
                Text($"{term.index + 1}.", 52, y, 10, "F2", 0.77, 0.58, 0.26);
                WrappedText(term.value, 74, y, 470, 10, "F1", 0.12, 0.08, 0.07, 3);
                y -= 32;
            }
        }

        public void Paragraph(string text)
        {
            EnsureSpace(42);
            WrappedText(text, 50, y, 500, 10, "F1", 0.12, 0.08, 0.07, 4);
            y -= 54;
        }

        public void Note(string text)
        {
            EnsureSpace(42);
            Fill(0.98, 0.96, 0.9);
            Rect(50, y - 36, 512, 36, fill: true);
            WrappedText(text, 64, y - 14, 480, 9, "F1", 0.28, 0.18, 0.12, 2);
            y -= 54;
        }

        public void SignatureLines(string leftLabel, string rightLabel)
        {
            EnsureSpace(70);
            Stroke(0.55, 0.48, 0.38);
            Line(50, y - 32, 260, y - 32);
            Line(352, y - 32, 562, y - 32);
            Text(leftLabel, 50, y - 48, 9, "F1", 0.3, 0.24, 0.18);
            Text(rightLabel, 352, y - 48, 9, "F1", 0.3, 0.24, 0.18);
            y -= 70;
        }

        public void Footer(int orderId)
        {
            Stroke(0.88, 0.84, 0.76);
            Line(50, 48, 562, 48);
            Text($"{ProjectBranding.FullName}  |  Order #{orderId}", 50, 32, 8, "F1", 0.45, 0.38, 0.3);
            Text("Generated document", 466, 32, 8, "F1", 0.45, 0.38, 0.3);
        }

        public byte[] ToBytes()
        {
            var stream = content.ToString();
            var objects = new List<string>
            {
                "<< /Type /Catalog /Pages 2 0 R >>",
                "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
                "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
                "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
                "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
                $"<< /Length {Encoding.ASCII.GetByteCount(stream)} >>\nstream\n{stream}endstream"
            };

            var pdf = new StringBuilder("%PDF-1.4\n");
            pdf.AppendLine($"% {Normalize(documentTitle)}");
            var offsets = new List<int> { 0 };
            foreach (var obj in objects.Select((value, index) => new { value, index }))
            {
                offsets.Add(Encoding.ASCII.GetByteCount(pdf.ToString()));
                pdf.AppendLine($"{obj.index + 1} 0 obj");
                pdf.AppendLine(obj.value);
                pdf.AppendLine("endobj");
            }

            var xref = Encoding.ASCII.GetByteCount(pdf.ToString());
            pdf.AppendLine("xref");
            pdf.AppendLine($"0 {objects.Count + 1}");
            pdf.AppendLine("0000000000 65535 f ");
            foreach (var offset in offsets.Skip(1))
            {
                pdf.AppendLine($"{offset:0000000000} 00000 n ");
            }
            pdf.AppendLine("trailer");
            pdf.AppendLine($"<< /Size {objects.Count + 1} /Root 1 0 R >>");
            pdf.AppendLine("startxref");
            pdf.AppendLine(xref.ToString(CultureInfo.InvariantCulture));
            pdf.AppendLine("%%EOF");
            return Encoding.ASCII.GetBytes(pdf.ToString());
        }

        private void EnsureSpace(double needed)
        {
            if (y - needed > 70) return;
            y = 110;
        }

        private void WrappedText(string text, double x, double startY, double width, double size, string font, double r, double g, double b, int maxLines)
        {
            var words = Normalize(text).Split(' ', StringSplitOptions.RemoveEmptyEntries);
            var lines = new List<string>();
            var line = "";
            var maxChars = Math.Max(12, (int)(width / (size * 0.52)));
            foreach (var word in words)
            {
                var candidate = string.IsNullOrWhiteSpace(line) ? word : $"{line} {word}";
                if (candidate.Length > maxChars)
                {
                    lines.Add(line);
                    line = word;
                }
                else
                {
                    line = candidate;
                }

                if (lines.Count == maxLines) break;
            }
            if (lines.Count < maxLines && !string.IsNullOrWhiteSpace(line))
            {
                lines.Add(line);
            }

            for (var i = 0; i < lines.Count; i++)
            {
                var final = i == maxLines - 1 && words.Length > string.Join(" ", lines).Split(' ', StringSplitOptions.RemoveEmptyEntries).Length
                    ? TrimTo(lines[i], Math.Max(8, maxChars - 3)) + "..."
                    : lines[i];
                Text(final, x, startY - i * (size + 3), size, font, r, g, b);
            }
        }

        private void Text(string value, double x, double yValue, double size, string font, double r, double g, double b)
        {
            content.AppendLine($"{N(r)} {N(g)} {N(b)} rg");
            content.AppendLine($"BT /{font} {N(size)} Tf {N(x)} {N(yValue)} Td ({Escape(Normalize(value))}) Tj ET");
        }

        private void Line(double x1, double y1, double x2, double y2) =>
            content.AppendLine($"{N(x1)} {N(y1)} m {N(x2)} {N(y2)} l S");

        private void Rect(double x, double yValue, double width, double height, bool fill) =>
            content.AppendLine($"{N(x)} {N(yValue)} {N(width)} {N(height)} re {(fill ? "f" : "S")}");

        private void Fill(double r, double g, double b) =>
            content.AppendLine($"{N(r)} {N(g)} {N(b)} rg");

        private void Stroke(double r, double g, double b) =>
            content.AppendLine($"{N(r)} {N(g)} {N(b)} RG");

        private void CircleApprox(double cx, double cy, double radius)
        {
            Stroke(0.77, 0.58, 0.26);
            content.AppendLine($"{N(cx + radius)} {N(cy)} m");
            content.AppendLine($"{N(cx + radius)} {N(cy + radius * 0.55)} {N(cx + radius * 0.55)} {N(cy + radius)} {N(cx)} {N(cy + radius)} c");
            content.AppendLine($"{N(cx - radius * 0.55)} {N(cy + radius)} {N(cx - radius)} {N(cy + radius * 0.55)} {N(cx - radius)} {N(cy)} c");
            content.AppendLine($"{N(cx - radius)} {N(cy - radius * 0.55)} {N(cx - radius * 0.55)} {N(cy - radius)} {N(cx)} {N(cy - radius)} c");
            content.AppendLine($"{N(cx + radius * 0.55)} {N(cy - radius)} {N(cx + radius)} {N(cy - radius * 0.55)} {N(cx + radius)} {N(cy)} c S");
        }

        private static string N(double value) => value.ToString("0.##", CultureInfo.InvariantCulture);

        private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");

        private static string TrimTo(string text, int length) => text.Length <= length ? text : text[..length];

        private static string Normalize(string? value)
        {
            return (value ?? "")
                .Replace("₺", "TL ")
                .Replace("Ç", "C").Replace("ç", "c")
                .Replace("Ğ", "G").Replace("ğ", "g")
                .Replace("İ", "I").Replace("ı", "i")
                .Replace("Ö", "O").Replace("ö", "o")
                .Replace("Ş", "S").Replace("ş", "s")
                .Replace("Ü", "U").Replace("ü", "u")
                .Replace("–", "-").Replace("—", "-")
                .Replace("\r", " ").Replace("\n", " ");
        }
    }
}
